server:
  port: 8080



spring:

  application: #服务名
    name: my-security
  profiles: #默认环境
    active: dev

  datasource: #数据库配置
    url: jdbc:mysql://localhost:3306/kanojo-authority?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gongbo2004520tr
    type: com.alibaba.druid.pool.DruidDataSource

  mvc: #防止swagger报错
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus: #mybatisplus配置
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: isDeleted
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jetcache: #阿里缓存框架配置
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    sms:
      type: redis
      port: 6379
      host: localhost
      valueEncoder: java
      valueDecoder: java
      keyConvertor: fastjson
      poolConfig:
        maxTotal: 50
    default:
      type: redis
      port: 6379
      host: localhost
      valueEncoder: java
      valueDecoder: java
      keyConvertor: fastjson
      poolConfig:
        maxTotal: 50